### ISSUE TITLE
How to override style and icon?

### ISSUE THREAD

**Issue by ding-qin** [rsaenen/ngx-input-file#12]
ngx-input-file version: 2.0.2
Angular: 6.0.6
Angular Material: 6.3.0

**Current behavior**

    - <mat-icon>add</mat-icon> is used by default
    - No simple way to override .file-button style.

**Expected/desired behavior**

    - Allow to change to any other material icons.
    - Override .file-button css style

**Comment by rsaenen** [comment]
**Icon** will be released with the next version.

Overriding style is native, so you can do it.

**Comment by rsaenen** [comment]
Released with 2.1.1

**Comment by solar95** [comment]
How can I add a progress bar ?
