### ISSUE TITLE
Bug: formControlname (case sensitive)

### ISSUE THREAD

**Issue by ding-qin** [rsaenen/ngx-input-file#13]
**Current behavior**

    - In the sample, it uses formControlName (Capital 'N')

**Expected/desired behavior**

    - formControlname (Lowercase 'n')

**Comment by rsaenen** [comment]
This directive is packaged with Angular:
https://angular.io/api/forms/FormControlName

As you can see, FormControlname doesn't exist:
https://angular.io/api/forms/FormControlname

This is not an issue or a bug.
