### ISSUE TITLE
Has no exported member 'InputFileConfig'.

### ISSUE THREAD

**Issue by LucasGSGS** [rsaenen/ngx-input-file#14]
**IMPORTANT:**
_Please be specific with an example. An issue with_ 
I used the same code as in demo, but I always got node_modules/ngx-input-file/ngx-input-file has no exported member 'InputFileConfig' error.

**Environment information**

    - OS: Mac
    - Angular Version: 5.2.0
    - Typescript version: ~2.5.3
    - npm version: 6.1.0
    - Node Version: 8.11.3

**Other information**

**Comment by rsaenen** [comment]
Released with 2.1.3
