### ISSUE TITLE
Stackblitz example not working

### ISSUE THREAD

**Issue by 360art** [rsaenen/ngx-input-file#15]
Stackblitz example is in endless loading state. There are some problems with fetching material design icons dependency. Tested on Firefox 62.0.2 and Chrome Version 69.0.3497.100. Windows 10 64bit.

**Comment by rsaenen** [comment]
For now, Stackblitz can't update its dependencies. As `material-design-icons` is a peerDependency, Stackblitz forces to install this package but always throws an error.

I'm working on it.

**Comment by rsaenen** [comment]
Done.
