### ISSUE TITLE
iconAdd not working when using fontawesome icon.

### ISSUE THREAD

**Issue by kevpeisker** [rsaenen/ngx-input-file#17]
**IMPORTANT:**
_Please be specific with an example. An issue with_ 

Using the iconAdd configuration and component attribute field. When I use my downloaded icon in 'iconAdd', the icon is not rendered.  Is there support for anything other than mat-icons?

**Expected/desired behavior**

To be able to use a fontawesome icon rather than a the default add icon.

**Comment by rsaenen** [comment]
Actually only material icons is supported.
I can let you register an icon with material and use it in the next release

**Comment by kevpeisker** [comment]
I no longer need this support. I appreciate it the offer though. Thanks!
