### ISSUE TITLE
probleme with displaying images, after deleting one

### ISSUE THREAD

**Issue by simorijal** [rsaenen/ngx-input-file#18]
**IMPORTANT:**
_Please be specific with an example. An issue with_ 

**Steps to reproduce and a minimal demo**
- i'm using rest back end to get images
-  preload inputFilelComponent with the images like :
...
 @ViewChild(InputFileComponent)
...
this.InputFileComponent.files.push({link: url, file: new File([url], name, {type: imageType} ), preview: url});

**Current behavior**

    - first the images are well displayed
    - once i click delete icon on any image, the image is deleted but the remainning images are not displayed correctly

**Expected/desired behavior**

    - 

**Environment information**

 Angular CLI: 6.0.8
Node: 9.0.0
OS: darwin x64
Angular: 6.1.10
bootstrap 4

**Other information**

**Comment by rsaenen** [comment]
Can you fork the stackblitz example and try it as I don't reproduce this issue?
https://stackblitz.com/edit/ngx-input-file

**Comment by rsaenen** [comment]
Closed due to lack of response.
