### ISSUE TITLE
Preview of uploaded image in edit component.

### ISSUE THREAD

**Issue by jarekkowol** [rsaenen/ngx-input-file#19]
Uploading works perfectly. I accept only and only one image.
When I select my image from disk or paste url then i se preview. It works perfectly too.

But in my component to Edit I need to show preview of image. My service return model with URL to previously uploaded image.

How to show preview of image in input-file component? It is possible?

This is my form:

```
        return this.formBuilder.group({
            .....
            icon: new FormControl([])
        });
```

This is my template:
```
                <input-file
                        [formControlName]="'icon'"
                        linkEnabled="true">
                </input-file>
```

**Comment by rsaenen** [comment]
Assuming your image class is:
```typescript
export class Image {
  path: string;
}

// Your component
this.form.controls.icon.setValue([{
  preview: image.path // path is what you get from your service
}])
```
You can import interface `InputFile` from `ngx-input-file`.
