### ISSUE TITLE
ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by DmitriyPotapov** [rsaenen/ngx-input-file#20]
**IMPORTANT:**
_Please be specific with an example. An issue with_ 

**Steps to reproduce and a minimal demo**
1. Set  **changeDetection** value for _Component_ decorator to "**ChangeDetectionStrategy.OnPush**"
2. Try to select some file\files
3. Now selected files values not in ngModel or FormControl
4. Click outside from InputFile control ot click on add icon 
5. Now selected files values pass to ngModel or FormControl

**Current behavior**

    -  Demo on StackBlitz https://stackblitz.com/edit/ngx-input-file-ykj3ux

**Expected/desired behavior**

    - 

**Environment information**

    - OS: 
    - Angular Version: 
    - Typescript version:
    - npm version: 
    - Node Version: 

**Other information**

**Comment by rsaenen** [comment]
As the ChangeDetectionStrategy is set to OnPush, this is the expected behavior.
You have to run `detectChanges()` from `ChangeDetectorRef` after adding files.

You can plug it on `acceptedFile()` output.

**Comment by DmitriyPotapov** [comment]
> As the ChangeDetectionStrategy is set to OnPush, this is the expected behavior.
> You have to run `detectChanges()` from `ChangeDetectorRef` after adding files.
> 
> You can plug it on `acceptedFile()` output.

I tried to call detectChanges in StackBlitz demo, this did not fix the problem.

P.S. StackBlitz  demo now updated

**Comment by rsaenen** [comment]
You can run your changeDetection on angular hook likes ViewChecked or DoCheck but I guess the better choice is to remove ChangeDetectionStrategy.OnPush or create a component with controlValueAccessor to encapsulate ngx-input-file (I use this solution on my projects)

**Comment by DmitriyPotapov** [comment]
thanks
