### ISSUE TITLE
Overwrite form control InputFile on custom data. 

### ISSUE THREAD

**Issue by jarekkowol** [rsaenen/ngx-input-file#21]
I have form group consist with some text input and one ngx-input-file (named image).
I'm selecting my image and then immediately upload to server. My service return URL to uploaded image. 

My goal is overwrite image form control with returned URL. Like this:

```
<input-file
    formControlName="image"
    (acceptedFile)="acceptedImage($event)">
</input-file>


    public acceptedImage(file: InputFile): void {
        this.service.uploadImage(file)
            .subscribe(
                data => {
                    this.form.value.image = data.url;
                });
    }
```

All works properly! But when I edit any other form control i lost my overwritten data.
My image from control again is InputFile object. Any solution?

**Comment by rsaenen** [comment]
To override the type you need to encapsulate the component with an implementation of ControlValueAccessor, this is the easiest way so far
