### ISSUE TITLE
Problem with file sizes

### ISSUE THREAD

**Issue by jnavarrovera** [rsaenen/ngx-input-file#23]
Hi,

I have an issue when I try to load a big image (>15 MB), it thows an error by console (RangeError: Maximum call stack size exceeded) and freeze the app.

**Steps to reproduce**

    - Select an +15 MB image 

**Current behavior**

    - 
![image](https://user-images.githubusercontent.com/38717794/51730951-b1f0f100-2079-11e9-85ff-0a3ace6e4607.png)

**Expected/desired behavior**

    - It should not freeze an handle the exception.

**Environment information**

    - OS: Windows 10
    - Angular Version: cli 6.2.5 
    - Typescript version: 7
    - npm version: 6.4.1
    - Node Version: 10.13.0

**Other information**
The images I'm been trying were JPG

**Comment by rsaenen** [comment]
Hi,
You can set a `sizeLimit` to avoid this behaviour.

As this package uses a native function to display the image:
```typescript
   /**
     * Sets the file preview with FileReader.
     */
    private setFilePreview(): void {
        for (const index in this.files) {
            if (this.files[index].file != null && this.inputFileService.typeGuard(this.files[index].file, 'image/*')) {
                const fr = new FileReader();
                fr.onload = () => {
                    this.files[index].preview = fr.result;
                };
                fr.readAsDataURL(this.files[index].file);
            }
        }
    }
```

I guess this issue is linked to your cpu... I tried to load an image > 30MB and everything was fine.

**Comment by jnavarrovera** [comment]
I was setting the sizeLimit under the size of the image, but I think it's processing the file before check the size.

I finaly make my own component, and I can check the size limit with no exceptions.

**Comment by rsaenen** [comment]
Feel free to contribute to this package too!
