### ISSUE TITLE
Custom validation and set file limit infinite

### ISSUE THREAD

**Issue by venkateshparihar** [rsaenen/ngx-input-file#24]
how to set file limit to infinite and how can i give validation on accepted file using control accessor

**Comment by rsaenen** [comment]
You can use https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Number/MAX_SAFE_INTEGER

A best pratice would be to encapsulate the input-file with a component which implements ControlValueAccessor.
