### ISSUE TITLE
Has a way to increase the preview image size?

### ISSUE THREAD

**Issue by matheusmqar** [rsaenen/ngx-input-file#25]
As I see the preview show the image in 160pixels x 160pixels.

Has a way to increase the preview image size? But only for one "file input"
LIke to 320pixels x 320pixels or higher...

Thanks xD

**Comment by rsaenen** [comment]
I would export a mixin:
https://github.com/rsaenen/ngx-input-file/blob/master/src/lib/components/input-file/input-file.scss

To let user do:
`@include input-file(10rem, 10rem, 2.5rem);`

When I published this file, I don't know how to do this.
