### ISSUE TITLE
Drag/Drop does not work with Safari

### ISSUE THREAD

**Issue by troymjones** [rsaenen/ngx-input-file#28]
**Steps to reproduce and a minimal demo**

    - Open Safari here: https://ngx-input-file.stackblitz.io/

**Current behavior**

    -  Drag and Drop does not work with Safari
    -  Stackblitz demo does not load with Safari
    -  It works to click and upload a file on my app via Safari but NOT drag/drop

**Expected/desired behavior**

    - Safari is supported without errors

**Environment information**

    - OS: macOS Mojave 10.14.6
    - Browser: Safari 12.1.2
    - Angular Version: ^7.2.0
    - Typescript version: ^3.2.4
    - npm version: 6.9.0
    - Node Version: 10.16.0
    - ngx-input-file version: ^7.0.1

**Other information**

    -  ReferenceError: Can't find variable: DragEvent

**Comment by rsaenen** [comment]
As I don't have a Mac, I can't check this issue.

Any PR would be appreciated.

**Comment by ErickXavier** [comment]
Hi @rsaenen , there's a problem on OSX and iOS devices that they dont have the DragEvent (and probably the DropEvent as well), the solution would be to replace them with "any".

The website browserstack.com has a trial you can use to test it.

Check the screenshot:
![Captura de Tela 2019-08-07 às 14 50 24](https://user-images.githubusercontent.com/648239/62645818-628e5600-b923-11e9-8a96-2ec463d13fd6.png)

**Comment by rsaenen** [comment]
Released with 8.0.1

**Comment by ErickXavier** [comment]
> Released with 8.0.1

Hey man, thanks for the quick response! ;) Project is running! lol
