### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by andjiev** [rsaenen/ngx-input-file#3]
![image](https://user-images.githubusercontent.com/18577061/36230293-41a63f9e-11da-11e8-8111-44b03fd8a739.png)

There is an issue using file explorer when i add the last file. Drag and drop is fine and limit is set to 4.
Angular v5

**Comment by rsaenen** [comment]
Before I correct this issue, can you show what contain the attribute `file` of each files.

**Comment by andjiev** [comment]
![image](https://user-images.githubusercontent.com/18577061/36341735-2a6e8140-13f3-11e8-8e25-d6d7b2db1996.png)
I'm uploading images only.

**Comment by rsaenen** [comment]
Can you reproduce this issue with the demo of this repository?

I push a correction by the way that I will publish on npm if it's working as I can reproduce this issue.

**Comment by andjiev** [comment]
Okay it's fixed. Thank you.

**Comment by andjiev** [comment]
For previewing images i think that u can use

` public getObjectUrl(file: File): SafeResourceUrl {
        return this.sanitizer.bypassSecurityTrustResourceUrl(window.URL.createObjectURL(file));
   }`
It creates smaller url instead of using a very long bas64 string.

**Comment by rsaenen** [comment]
I will publish a new release.
Please make a pull request to improve this package, I thank you in advance!

**Comment by rsaenen** [comment]
Released with 1.0.1
