### ISSUE TITLE
How to get the file blob

### ISSUE THREAD

**Issue by iron2414** [rsaenen/ngx-input-file#32]
How do i get the file's blob once i submit the form?
I have a form with a few fields, and used console log on the submitted form.

![image](https://user-images.githubusercontent.com/10381571/64924496-5d0b1200-d7e5-11e9-864d-4051b68c98ec.png)

As you can see, at the "form.value.pdf" there are the files, however it has no "file" attribute like shown in the example
(const formData = new FormData();
    formData.append('file', file.file, file.file.name); 
 And there are a few meta-data but no blob content for me. How do i get that?

My relevant html look like this:
![image](https://user-images.githubusercontent.com/10381571/64924516-ae1b0600-d7e5-11e9-9baa-6e821c1ddd9f.png)

**Comment by rsaenen** [comment]
You get an array of InputFile so the property file does not exist on an array.

**Comment by iron2414** [comment]
Sorry i'm a bit new to this, so i don't understand. But i don't need the property, i need the binary itself?

**Comment by rsaenen** [comment]
As you get an array, try pdf[0].file, it's pure javascript as this point ;)

**Comment by iron2414** [comment]
But as you can see on my picture pdf[0] is a file. And it has lots of properties "name" and such, but i the file's content is not there. This is why i'm asking how can i get the blob, or the content's.

**Comment by rsaenen** [comment]
It's an `InputFile` exported by this package.
The property `file` is a `File` exported by dom.lib.ts which is native javascript.

So `file` contains the file selected.
At this point, you have to check the documentation of the class `File` to see what you want exactly.
