### ISSUE TITLE
ngx-input-file sizeLimit no funciona

### ISSUE THREAD

**Issue by jame0928** [rsaenen/ngx-input-file#36]
Estoy implementando el ngx-input-file en mi aplicacion angular, sin embargo aunque le pongo un tamaño maximo al archivo sizeLimit="50", si intento subir un archivo de 100kb me lo procesa sin verificar el tamaño maximo. Incluso si se hacemos la prueba en [ https://stackblitz.com/edit/ngx-input-file](url) tambien tiene el mismo comportamiento. Este es el ejemplo que estaba intentando

`<input-file placeholder="Drop files below!" fileLimit="1" sizeLimit="50"></input-file>` pero el sizeLimit no tiene ningun efecto. Agradezco cualquier indicacion.

**Comment by peterciprian** [comment]
I tried the same, added the attribute `sizeLimit="200"` to the `<input-file>` tag, but it does nothing at all. How should it be working?

**Comment by namnguyen51** [comment]
Input size in MB, not KB. Maube author mistake

**Comment by szymonbartnik** [comment]
please update documentation ;)

**Comment by szymonbartnik** [comment]
it's closed by docs still has information about kb :D 

![image](https://user-images.githubusercontent.com/46488148/102719039-d4cec300-42eb-11eb-8e00-f073f65078fe.png)
