### ISSUE TITLE
Hide/remove all the buttons

### ISSUE THREAD

**Issue by mattiasnordqvist** [rsaenen/ngx-input-file#4]
All we need is the upload-box, we don't need the upload/remove/select-buttons. Is it possible, or would it be easy to implement a way to not show them?

**Comment by rsaenen** [comment]
I'm not sure to understant what you want...
What's the "upload-box"? The drag and drop zone?

**Comment by mattiasnordqvist** [comment]
yes exactly. All I need is actually the drop zone and the api+events. Maybe it'd be easier to just not use ngx-input-file? 😆

**Comment by rsaenen** [comment]
Feel free to look at the source code, the licence is MIT.
You can also contribute to this repository ;)

**Comment by mattiasnordqvist** [comment]
Maybe I will. :)
