### ISSUE TITLE
How to remove font awesome icon

### ISSUE THREAD

**Issue by binishprabhakar** [rsaenen/ngx-input-file#9]
There is any option is available to remove <i _ngcontent-c6="" aria-hidden="true" class="fas fa-folder-open"></i>.

**Comment by rsaenen** [comment]
No there is not a option to remove font awesome as nothing will display if font awesome is not included.
You can contribute if you want it :)

**Comment by binishprabhakar** [comment]
Ok there is any option to remove preview option

**Comment by binishprabhakar** [comment]
Thanks 👍
